name: DevOps Lab Exercise
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Correct indentation

    steps:
      - name: Checkout code  # Added step name for clarity
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      # Uncomment the line below if you want to install npm dependencies
        - run: npm ci

      - run: npm run build --if-present
      - run: npm test
